# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LKWallpaper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry'
  # Pods for LKWallpaper
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'YYModel'
pod 'AFNetworking'
pod 'Bugly'
end
